Rails:
    Enabled: true
AllCops:
  Exclude:
   - bin/*
   - config/**/*
   - db/**/*
   - local/**/*
   - vendor/**/*
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
