default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['KOTOGRAM_DATABASE_USER'] %>
  password: <%= ENV['KOTOGRAM_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: kotogram_development


test:
  <<: *default
  database: kotogram_test

staging:
  <<: *default
  database: kotogram_staging
  username: root
  password: <%= ENV['KOTOGRAM_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: kotogram_production
  username: <%= ENV['KOTOGRAM_DATABASE_USER'] %>
  password: <%= ENV['KOTOGRAM_DATABASE_PASSWORD'] %>
